# Generated by Django 4.1.7 on 2023-03-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_db',
        ),
    ]
